### ISSUE TITLE
Add a dynamic converted function that should be able to convert multiple units to multiple

### ISSUE THREAD

**Issue by Saif64** [Fahim-ok/391-Javascript#1]

**Comment by Saif64** [comment]
kindly assign it to me. Let me implement the function. This will be contributed in your repository. Very good Win-win situtaion

**Comment by Saif64** [comment]
kindly assign it to me. Let me implement the function. This will be contributed in your repository. Very good Win-win situtaion

**Comment by Fahim-ok** [comment]
Yeah sent the invitation brother.

**Comment by Saif64** [comment]
done. You can close the issue now.
